= Wireless Tower
The Wireless Tower is a building that can connect a network across a distance without the need for cables.
wireless towers act as a wireless hub/access point that can only link to Ground Antennas. but can have multiple Ground Antennas linked.

The GUI shows connected ground antennas and lets you link/unlink them easily, you can rename the Tower from the top bar above the map for easy identification.

[NOTE]
====
linked Towers/Ground Antennas have unlimited range between them but an increase of power draw depending on how far apart they are from each other.
====

Wireless Towers also act as a Wireless Access point for the Wireless Tablet with Broadcasting range of 40m and a max range of 490M with the use of Wireless Range Extenders

== Wireless Ground Antennas
Wireless Ground Antennas act as a remote transceiver/client, connecting to a Wireless Tower to allow transmission of a network to multiple locations.

Wireless Ground Antennas will only connect to a Wireless Tower. but one tower can have multiple Ground Antennas linked. you can rename the Antenna in the GUI

[NOTE]
====
you can click on a different Tower/Antenna in the GUI and it will place the Guid into the Link Tower input box to allow for easy linking.
====

== Wireless Access Point
The Wireless Access Point allows for the Wireless Tablet to connect to the network at a limited range.

[NOTE]
====
The upgrades for this is found in the DS tab of the MAM
====

== Wireless Tablet
The Wireless Tablet acts like a portable Storage Terminal for viewing and retrieving items from the connected network.

The filter tab allows you to extract items from the network directly into your inventory as long as the Tablet is in range of the network
you can set the item to go into a slot you choose and have a full stack or an exact amount to be transferred.

[NOTE]
====
If there are more items in that slot i.e. 500 screws when you have a set amount of 100, the excess will be transferred back into the network as long as there is space.
====

== Wireless Range Extenders
Increases the range the Wireless Tower can broadcast the network to the Wireless Tablet.

[NOTE]
====
Every 20 extenders increase the broadcast range of the Wireless Tower by 18M using 500 of them to increase the range to 490M.
====