= Solar Panels

Solar Panels are one of the simplest renewable generators in Refined Power: place one, wire it up, and it produces power from the sun. They come in three tiers plus a set of roof panels. Higher tiers produce more power.

Unlike the xref:/rp/buildings/soalrpanels/solartower.adoc[Solar Power Tower], a Solar Panel generates electricity directly,it does not need xref:/rp/buildings/soalrpanels/solar-power-mirror.adoc[mirrors] or any downstream machine.

|===
| |Mk. 1 |Mk. 2 |Mk. 3 |Roof

|Building Cost
|4x Photovoltaic Cell
|10x Heavy Modular Frame +
30x Photovoltaic Cell +
20x Steel Pipe +
25x Cable
|10x Heavy Modular Frame +
40x Photovoltaic Cell +
25x Steel Pipe +
20x Cable +
100x Alclad Aluminium Sheet +
5x Computer
|3x Concrete +
4x Photovoltaic Cell

|Maximum Power Output
|8 MW
|75 MW
|150 MW
|20 MW
|===


== Milestones

|===
| |Mk. 1 |Mk. 2 |Mk. 3 | Roof

|Available with
|Tier 3: Refined Power Mk2
|Tier 5: Refined Power Solar Panels
|Tier 7: Refined Power Solar Panels
|- (Awesome Shop)*

|Research Cost
|200x Steel Pipe +
1 000x Wire +
50x Steel Beam
|100x Photovoltaic Cell +
500x Quickwire +
50x Heavy Modular Frame
|100x Photovoltaic Cell +
500x Quickwire +
50x Heavy Modular Frame +
200x Alclad Aluminium Sheets
| - (5x Ficsit Coupon)
|===

*{sp}To unlock it in the Awesome Shop, first you have to unlock Mk. 1 solar panels and roofs.

== Tips

* *Solar is fully passive.* No fuel, no belts, no pipes. Along with wind, it is the lowest-maintenance power in the mod.
* *Solar production is reduced or completely stopped at night.* If you rely on them, pair them with batteries or an on-demand power source such as biomass burners.

== See also

* xref:/rp/buildings/solarpanels/solartower.adoc[Solar Power Tower] 
* xref:/rp/buildings/windturbines/index.adoc[Wind Turbine] 
* xref:/rp/buildings/waterturbines/index.adoc[Water Turbine] 

== References and Links

* link:https://ficsit.app/mod/RefinedPower[Refined Power Mod on ficsit.app]
* link:https://discord.com/invite/refined-r-d-729807284103806981[Official Discord]
* link:https://docs.ficsit.app/refinedrd/latest/rp/index.html[Refined Power Documentation]
